/******************************************************************************/
/***         Generated by IBExpert 2020.4.21.2 07/04/2022 21:04:41          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

SET CLIENTLIB 'C:\PROJETOS\DELPHI\TOTALL\LIB\fbclient.dll';

CONNECT '127.0.0.1/3030:C:\PROJETOS\DELPHI\TOTALL\DATABASE\SGCPFJ.fdb' USER 'SYSDBA' PASSWORD 'masterkey';



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE CEP (
    CEP         VARCHAR(11) NOT NULL,
    LOGRADOURO  VARCHAR(50),
    BAIRRO      VARCHAR(50),
    LOCALIDADE  VARCHAR(50),
    UF          VARCHAR(2)
);

CREATE TABLE CNPJ (
    CNPJ        VARCHAR(14) NOT NULL,
    NOME        VARCHAR(50),
    FANTASIA    VARCHAR(50),
    CEP         VARCHAR(11),
    LOGRADOURO  VARCHAR(50),
    NUMERO      VARCHAR(11),
    BAIRRO      VARCHAR(50),
    MUNICIPIO   VARCHAR(50),
    UF          VARCHAR(2)
);



/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE CEP ADD CONSTRAINT PK_CEP PRIMARY KEY (CEP);
ALTER TABLE CNPJ ADD CONSTRAINT PK_CNPJ PRIMARY KEY (CNPJ);
